Algoritmo "Enquanto"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2026
Var

   i, n: inteiro

Inicio

   escreval("Até quando deseja contar: ")
   leia(n)

   i <-1

   escreval("Contando até ", n)

   //ESTRUTURA DE REPETIÇÃO ENQUANTO

   enquanto i <= n faca
      escreval(i)
      i<-i+1
   fimenquanto

   escreval("Contagem finalizada")

Fimalgoritmo