Algoritmo "Exercicio05"
// 
//  
// Descrição   : Crie um algoritmo que leia umm numero inteiro N e mostre
//todos os multiplos de 5 entre 1 e N
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/09/2026
Var

i, numero:inteiro


Inicio

escreval("Digite um numero: ")
leia(numero)

para i de 1 ate numero faca
    se i % 5 = 0 entao
        escreval(i)
    fimse
fimpara


Fimalgoritmo