Algoritmo "Exercicio01"

Var
   quantidade: inteiro
   valorUnitario, total: real

Inicio
   valorUnitario <- 18.50

   escreval("=== TABELA DE PREÇOS - CADERNOS ===")
   escreval("------------------------------------")

   para quantidade de 1 ate 10 faca
      total <- quantidade * valorUnitario
      escreval(quantidade, " caderno(s) = R$ ", total:4:2)
   fimpara

   escreval("------------------------------------")

Fimalgoritmo