Algoritmo "Multicaso"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2026
Var

   conceito: caractere

Inicio

   escreval("Digite o conceito do aluno (por letra A ate D): ")
   leia(conceito)

   escolha conceito
   caso "A"
      escreva("Execelente")
   caso "B"
      escreva("Bom")
   caso "C"
      escreva("Regular")
   caso "D"
      escreva("Insuficiente")
   outrocaso
      escreva("Invalido")
   fimescolha


Fimalgoritmo