Algoritmo "Exercicio06"
// 
//  
// Descrição   : leia a temperatura em graus Celsius e converta em fahrenheit
// (F=(cx9/5)+ 32)
// Autor(a)    : Juliano Ferreira
// Data atual  : 02/09/2026
Var

celsius, fahrenheit: real    //declaracao de variavel

Inicio

escreva("Digite os graus em Celsius: ")
leia(celsius)                               //entrada de dados pelo usuario

fahrenheit <- (celsius * 9/5) + 32       //funcao que transforma ºc em ºf

escreval("Conversão de Celsius para Fahreinheit é: ", fahrenheit)
//imprime o resultado a conversao

Fimalgoritmo