Algoritmo "Exercicio3"
// 
//  
// Descrição   : crie um algoritmo que calcule a area de um triangulo,
//formula: area = (base*altura)/2
// Autor(a)    : Juliano Ferreira
// Data atual  : 02/09/2026
Var

area, base, altura: real     //declaracao de variaveis

Inicio

escreva("Digite a base do triângulo: ")   //entrada de dados
leia(base)
escreva("Digite a altura do triângulo: ")  //entrada de dados
leia(altura)

area <- (base*altura)/2    //funcao do calculo da areo do triangulo

escreval("A área do triângulo é: ", area)  // imprime a area do triangulo

Fimalgoritmo