Algoritmo "Exercicio02"
// 
//  
// Descrição   : Crie um algoritmo que leia duas notas e calcule a media
// aritmetica
// Autor(a)    : Juliano Ferreira
// Data atual  : 02/09/2026
Var

notaA, notaB: inteiro          //declarao de variavel do tipo inteiro
media_aritmetica: real         //declaracao de variavel do tipo real

Inicio

escreva("Digita a nota 1: ")    //entrada de dados pelo usuario
leia(notaA)
escreva("Digite a nota 2: ")    //entrada de dados pelo usuario
leia(notaB)

media_aritmetica <- (notaA + notaB)/2  //funcao da media

escreval("A média aritmética é: ", media_aritmetica) //imprimir o resultado do calculo

Fimalgoritmo